# Generated by Django 5.1.1 on 2024-09-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.CharField(max_length=100)),
                ('construction_year', models.IntegerField()),
                ('details', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='property_photos/')),
            ],
        ),
    ]
